# Bitbucket Project Mapping: Core Integration
bitbucket_project_key=COREINT
bitbucket_project_name=core_integration-coreintegration
bitbucket_project_display=Core Integration
bitbucket_base_url=https://bitbucket.adidas.com
applicable_sources=s4hana,afs,wms,kafka,ems
applicable_targets=s4hana,afs,wms,kafka,ems
