# Bitbucket Project Mapping: Product Area - Inventory
bitbucket_project_key=PINV
bitbucket_project_name=product_area-inventory
bitbucket_project_display=Product Area - Inventory
bitbucket_base_url=https://bitbucket.adidas.com
applicable_sources=wms,s4hana
applicable_targets=afs,kafka,demandware
applicable_objects=inventory,stock,availability
