# Bitbucket Project Mapping: Product Area - Order
bitbucket_project_key=PORD
bitbucket_project_name=product_area-order
bitbucket_project_display=Product Area - Order Management
bitbucket_base_url=https://bitbucket.adidas.com
applicable_sources=demandware,salesforce,wms
applicable_targets=s4hana,afs,kafka
applicable_objects=order,salesorder,shipment,return
