# Bitbucket Project Mapping: Product Area - Article
bitbucket_project_key=PART
bitbucket_project_name=product_area-article
bitbucket_project_display=Product Area - Article
bitbucket_base_url=https://bitbucket.adidas.com
applicable_sources=s4hana,demandware,salesforce
applicable_targets=afs,kafka,demandware
applicable_objects=article,product,sku,style
